name: Build & deploy NBA-Go app

on:
  push: 
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy NBA-Go app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      #- name: Code test

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/nba-go:latest

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nba-go:latest
